package cp14_表明と単体テスト
/*
 * 表明と単体テスト
 * プロパティベースのテスト
 * ※ScalaCheckを使用してテストする。
 */
object No14_6 {
    def main(args: Array[String]) {
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...

        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...

        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...

        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...

        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...

        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
        //It Can't imported...//It Can't imported...//It Can't imported...//It Can't imported...
    }
}

